//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuadrantAnalysis.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuadrantAnalysis.Resources.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avg. Pedal Force (N).
        /// </summary>
        internal static string Label_AvgPedalForce {
            get {
                return ResourceManager.GetString("Label_AvgPedalForce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pedal Velocity (m/s).
        /// </summary>
        internal static string Label_CircumPedalVelocity {
            get {
                return ResourceManager.GetString("Label_CircumPedalVelocity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crank Length.
        /// </summary>
        internal static string Label_CrankLength {
            get {
                return ResourceManager.GetString("Label_CrankLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eval version supports 
        ///previous {0} days.
        ///Upgrade for unlimited
        ///access..
        /// </summary>
        internal static string Label_EvalLimit {
            get {
                return ResourceManager.GetString("Label_EvalLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Settings.
        /// </summary>
        internal static string Label_ListSettings {
            get {
                return ResourceManager.GetString("Label_ListSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quadrant Analysis.
        /// </summary>
        internal static string Label_QuadrantAnalysis {
            get {
                return ResourceManager.GetString("Label_QuadrantAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Charts.
        /// </summary>
        internal static string Label_SelectedCharts {
            get {
                return ResourceManager.GetString("Label_SelectedCharts", resourceCulture);
            }
        }
    }
}
